export const cvContent = {
  en: {
    name: "Smail Yazidi",
    title: "Web Developer",
    downloadCv: "Download CV",
    headings: {
      contact: "Contact",
      languages: "Languages",
      skills: "Skills",
      aboutMe: "About Me",
      education: "Education",
      experience: "Experience",
      programmingLanguages: "Programming Languages",
      frameworks: "Frameworks & Libraries",
      databases: "Databases",
      otherTechnicalSkills: "Other Technical Skills",
      softSkills: "Soft Skills",
    },
    contact: {
      phone: "0719270155",
      email: "smail.yazidi.work@gmail.com",
      location: "Ifrane, Morocco",
    },
    languages: {
      English: "Good",
      French: "Medium",
      Arabic: "Good",
      Amazigh: "Good",
    },
    skills: {
      programmingLanguages: ["JavaScript", "Python", "PHP", "Node.js"],
      frameworks: ["Laravel", "React.js"],
      databases: ["MySQL", "MongoDB"],
      other: [
        "PowerApps",
        "Technical Analysis",
        "Web Application Development",
        "Web Project Management",
        "Version Control: Git",
      ],
      softSkills: [
        "Teamwork",
        "Effective Communication",
        "Problem Solving",
        "Time Management",
        "Adaptability",
        "Critical Thinking",
        "Creativity",
        "Initiative",
      ],
    },
    aboutMe:
      "I am a dynamic and ambitious web developer with skills in building web applications. I hold a diploma in full-stack web development and received additional training from the Azrou Center for Community Development. I am seeking opportunities to apply my skills and contribute to a motivated and collaborative team.",
    education: [
      {
        title: "Web Development Training",
        institution: "Azrou Center for Community Development — Azrou",
        date: "2024 - 2025",
        description: "Intensive training program focused on modern web technologies.",
      },
      {
        title: "Full Stack Digital Web Development Diploma",
        institution: "Specialized Institute of Applied Technology – Ifrane (OFPPT)",
        date: "2022 - 2024",
        description: "Comprehensive program covering front-end and back-end development.",
      },
      {
        title: "Baccalaureate in Life and Earth Sciences",
        institution: "Qualifying High School Sidi El Makhfi",
        date: "2021",
        description: "High school diploma with a focus on science.",
      },
    ],
    experience: [
      {
        title: "Web Development Intern",
        company: "Al Akhawayn University",
        date: "June 10, 2025 – July 10, 2025",
        description: "Hands-on experience in developing and improving web applications.",
      },
      {
        title: "Web Development Intern",
        company: "Municipality of Sidi Mokhfi",
        date: "March 11, 2024 – April 11, 2024",
        description: "Applied technical skills in real projects and collaborated with a development team.",
      },
    ],
    portfolio: {
      cv: "https://smailyazidi.vercel.app/cv",
      website: "https://smailyazidi.vercel.app",
    },
  },
  fr: {
    name: "Smail Yazidi",
    title: "Développeur Web",
    downloadCv: "Télécharger CV",
    headings: {
      contact: "Contact",
      languages: "Langues",
      skills: "Compétences",
      aboutMe: "À Propos de Moi",
      education: "Formation",
      experience: "Expérience",
      programmingLanguages: "Langages de Programmation",
      frameworks: "Frameworks & Bibliothèques",
      databases: "Bases de Données",
      otherTechnicalSkills: "Autres Compétences Techniques",
      softSkills: "Compétences Non Techniques",
    },
    contact: {
      phone: "0719270155",
      email: "smail.yazidi.work@gmail.com",
      location: "Ifrane, Maroc",
    },
    languages: {
      Anglais: "Bon",
      Français: "Intermédiaire",
      Arabe: "Bien",
      Amazigh: "Bien",
    },
    skills: {
      programmingLanguages: ["JavaScript", "Python", "PHP", "Node.js"],
      frameworks: ["Laravel", "React.js"],
      databases: ["MySQL", "MongoDB"],
      other: [
        "PowerApps",
        "Analyse technique",
        "Développement d’applications web",
        "Gestion de projets web",
        "Gestion de version : Git",
      ],
      softSkills: [
        "Travail en équipe",
        "Communication efficace",
        "Résolution de problèmes",
        "Gestion du temps",
        "Adaptabilité",
        "Esprit critique",
        "Créativité",
        "Prise d’initiative",
      ],
    },
    aboutMe:
      "Je suis une personne dynamique et ambitieuse, spécialisée dans le développement web et les applications web. Diplômé en développement web full-stack et formé au Centre Azrou pour le Développement Communautaire, je souhaite mettre mes compétences à profit et intégrer une équipe motivée.",
    education: [
      {
        title: "Formation en Développement Web",
        institution: "Centre Azrou pour le Développement Communautaire",
        date: "2024 - 2025",
        description: "Formation en Développement Web.",
      },
      {
        title: "Diplôme en Développement Digital Web Full Stack",
        institution: "Institut Spécialisé de Technologie Appliquée Ifrane (OFPPT)",
        date: "2022 - 2024",
        description: "Formation complète en développement web full stack.",
      },
      {
        title: "Baccalauréat en Sciences de la Vie et de la Terre",
        institution: "Lycée Qualifiant Sidi El Makhfi",
        date: "2021",
        description: "Diplôme d'études secondaires.",
      },
    ],
    experience: [
      {
        title: "Stage en Développement Web",
        company: "Université Al Akhawayn",
        date: "10 juin 2025 – 10 juillet 2025",
        description: "Stage pratique en développement web avec participation active à des projets.",
      },
      {
        title: "Stage en Développement Web",
        company: "Commune de Sidi Mokhfi",
        date: "11 mars 2024 – 11 avril 2024",
        description: "Application des compétences techniques dans des projets réels et travail en équipe.",
      },
    ],
    portfolio: {
      cv: "https://smailyazidi.vercel.app/cv",
      website: "https://smailyazidi.vercel.app",
    },
  },
}
