export const cvContent = {
  fr: {
    name: "SMAIL YAZIDI",
    title: "Développeur Web",
    contact: "Contact",
    phone: "0719270155",
    email: "smail.yazidi.work@gmail.com",
    location: "IFRANE, MAROC",
    languages: "Langues",
    langMotherTongue: "Langue maternelle",
    langMedium: "moyen",
    arabic: "Arabe",
    amazigh: "Amazigh",
    french: "Français",
    english: "Anglais",
    skills: "Compétences",
    programmingLanguages: "Langages de programmation",
    frameworksLibraries: "Frameworks et bibliothèques",
    databases: "Bases de données",
    otherTechnicalSkills: "Autres compétences techniques",
    softSkills: "Compétences personnelles",
    aboutMe: "À propos de moi",
    aboutMeText:
      "Dynamique et ambitieux, je possède des compétences en développement web et applications web. Titulaire d'un diplôme en développement web full stack d'un institut de formation. Je cherche à appliquer mes compétences et à contribuer à une équipe dynamique.",
    education: "Formation",
    webDev: "Développement Web",
    centreAzrou: "Centre Azrou pour le Développement Communautaire",
    webDevTraining: "Formation en Développement Web.",
    fullStackDiploma: "Diplôme en Développement Digital Web Full Stack",
    istaIfrane: "Institut Spécialisé de Technologie Appliquée Ifrane (OFPPT)",
    fullStackTraining: "Formation complète en développement web full stack.",
    baccalaureate: "Baccalauréat en Sciences de la Vie et de la Terre",
    lyceeSidiMakhfi: "Lycée Qualifiant Sidi El Makhfi",
    highSchoolDiploma: "Diplôme d'études secondaires.",
    experience: "Expériences",
    webDevInternship: "Stage en Développement Web",
    alAkhawayn: "Université Al Akhawayn",
    practicalInternship: "Stage pratique en développement web.",
    communeSidiMokhfi: "Commune de Sidi Mokhfi",
    applicationSkills: "Application des compétences en développement web et contribution à une équipe dynamique.",
    downloadCv: "Télécharger le CV",
  },
  en: {
    name: "SMAIL YAZIDI",
    title: "Web Developer",
    contact: "Contact",
    phone: "0719270155",
    email: "smail.yazidi.work@gmail.com",
    location: "IFRANE, MOROCCO",
    languages: "Languages",
    langMotherTongue: "Native language",
    langMedium: "medium",
    arabic: "Arabic",
    amazigh: "Amazigh",
    french: "French",
    english: "English",
    skills: "Skills",
    programmingLanguages: "Programming Languages",
    frameworksLibraries: "Frameworks and Libraries",
    databases: "Databases",
    otherTechnicalSkills: "Other Technical Skills",
    softSkills: "Soft Skills",
    aboutMe: "About Me",
    aboutMeText:
      "Dynamic and ambitious, I possess skills in web and web application development. Holder of a full stack web development diploma from a training institute. I seek to apply my skills and contribute to a dynamic team.",
    education: "Education",
    webDev: "Web Development",
    centreAzrou: "Azrou Center for Community Development",
    webDevTraining: "Training in Web Development.",
    fullStackDiploma: "Full Stack Digital Web Development Diploma",
    istaIfrane: "Specialized Institute of Applied Technology Ifrane (OFPPT)",
    fullStackTraining: "Comprehensive training in full stack web development.",
    baccalaureate: "Baccalaureate in Life and Earth Sciences",
    lyceeSidiMakhfi: "Qualifying High School Sidi El Makhfi",
    highSchoolDiploma: "High school diploma.",
    experience: "Experience",
    webDevInternship: "Web Development Internship",
    alAkhawayn: "Al Akhawayn University",
    practicalInternship: "Practical internship in web development.",
    communeSidiMokhfi: "Municipality of Sidi Mokhfi",
    applicationSkills: "Application of web development skills and contribution to a dynamic team.",
    downloadCv: "Download CV",
  },
}
